# Generated by Django 4.0.6 on 2022-07-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_dob', models.CharField(max_length=20)),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('student_address', models.CharField(max_length=155)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
