# Generated by Django 4.0.6 on 2022-07-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_studentregistration_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='student_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
